# Generated by Django 4.1.2 on 2022-10-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th_digitized', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
