# Generated by Django 4.1.2 on 2022-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th_digitized', '0002_rename_partners_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.CharField(default='logo', max_length=200, verbose_name='logo'),
        ),
    ]
