# Generated by Django 4.1.2 on 2022-10-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th_digitized', '0003_partner_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='file name')),
                ('owner', models.CharField(max_length=200, verbose_name='Owner')),
                ('pdf', models.FileField(upload_to='uploads')),
                ('cover', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.CharField(default='logo', max_length=300, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(max_length=300, verbose_name='website link'),
        ),
    ]
