# Generated by Django 4.1.2 on 2022-10-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th_digitized', '0004_workplan_alter_partner_logo_alter_partner_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Organization logo'),
        ),
    ]
